#!/usr/bin/env bash

# !!! requires root !!!

set -e

# terminal colors
# background: #0E2E20
# foreground: #29E18C

# packages
apt-get update -y
apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-pip \
    python3-venv \
    ruby \
    ruby-dev \
    curl \
    tmux \
    tree \
    locate

# bashrc
cp ./bashrc_aliases ~/.bashrc_aliases
echo "source ~/.bashrc_aliases" >> ~/.bashrc

# git
git clone https://github.com/erikw/tmux-powerline.git ~/git/tmux-powerline/
cp ./gitconfig ~/.gitconfig
cp ./git-prompt.sh ~/.git-prompt.sh

# tmux
cp ./tmux.conf ~/.tmux.conf
cp ./tmux-powerlinerc ~/.tmux-powerlinerc

# vim
git clone https://github.com/vim/vim.git ~/git/vim/
CUR_DIR=$PWD
cd ~/git/vim/
./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp \
            --enable-python3interp \
            --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
            --enable-perlinterp \
            --enable-luainterp \
            --enable-cscope \
            --with-x \
            --with-compiledby="Logan Brooke"
make VIMRUNTIMEDIR=/usr/share/vim/vim74
make install
cd $CUR_DIR
cp ./vimrc ~/.vimrc
cp -r ./vim ~/.vim
