#!/usr/bin/env python3

import argparse
import subprocess
import sys


def main(base, bash, docker, git, golang, node_js, python_3, ruby, rust,
         themes_and_fonts, tmux, vim):
    commands = []

    if base:
        commands.append('./install-base.sh')

    if docker:
        commands.append('./install-docker.sh')

    if rust:
        commands.append('./install-rust.sh')

    if golang:
        commands.append('./install-golang.sh')

    if node_js:
        commands.append('./install-nodejs.sh')

    if ruby:
        commands.append('./install-ruby.sh')

    if python_3:
        commands.append('./install-python-3.sh')

    if bash:
        commands.append('./install-bash.sh')

    if git:
        commands.append('./install-git.sh')

    if tmux:
        commands.append('./install-tmux.sh')

    if vim:
        commands.append('./install-vim.sh')

    if themes_and_fonts:
        commands.append('./install-themes-and-fonts.sh')

    for command in commands:
        result = subrocess.run(command)
        if result.returncode != 0:
            print('Installation failed!')
            print('Failed step: ', command)
            sys.exit(1)

    print('Please log out and back in for all changes to take effect')
    print('Installation Complete!')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('-b', '--bash', action='store_true', help='Configure bash')
    parser.add_argument('-g', '--git', action='store_true', help='Configure git')
    parser.add_argument('-G', '--golang', action='store_true', help='Install golang and default global packages')
    parser.add_argument('-N', '--no-base', action='store_false', dest='base', help='Don\'t install base packages')
    parser.add_argument('-d', '--docker', action='store_true', help='Install docker')
    parser.add_argument('-n', '--node-js', action='store_true', help='Install node.js and default global packages')
    parser.add_argument('-p', '--python-3', action='store_true', help='Install global packages for python 3')
    parser.add_argument('-r', '--rust', action='store_true', help='Install rust and default global packages')
    parser.add_argument('-R', '--ruby', action='store_true', help='Install ruby and default global packages')
    parser.add_argument('-t', '--tmux', action='store_true', help='Install and configure tmux')
    parser.add_argument('-T', '--themes-and-fonts', action='store_true', help='Install extra themes and fonts')
    parser.add_argument('-v', '--vim', action='store_true', help='Install and configure vim')

    args = vars(parser.parse_args())

    print('Selected options:', *sorted(k for k, v in args.items() if v), sep='\n\t')

    main(**args)
